language: c
sudo: required
install:
- sudo apt-get update
- sudo apt-get install lua5.1 luarocks p7zip-full python-sphinx
- sudo luarocks install penlight
- gem install github_changelog_generator
script:
- bash travis.sh
notifications:
  email:
    on_failure: always
    on_success: change
env:
  global:
  - GH_REF=github.com/druuimai/m-mf.git
  - GH_USER=druuimai-machine-account
  - secure: OOCL1vPHurvKqaGnOwaX4hy1qq445CsQtJCeK2FzDYCq4iqYKzGEU510vjOgdlWUplaho/hZE4VpZ6sfsf5VO2k/gYINiMqpIf64QjMKNqBSB5Cuhb3f0lTCp0bLkNpNB7d8WIFIHNvTwuQBf9m1rqmCa/psgV12YocvAQjdLR6AVmTg+J48xOpXYOTOYlLn0b2WnXAN3wyAZ+zca5dr3eO6FfMH4P89zuZeQ+gAA2tQT3XjrxRL1dp+f1+3GXv4bdmjQgQf0z+Lxag/wMfW6BpNP7JjYdU9N6VO9AvAL5GPAXn+0UiTZEhPdP5CSAggkDRDutBsyq+y/bCT6XQS8vl2hu5H0TDiheUX0ovUVmZSiL45LntGXes9TA6ZTl6Om1yW+T7LafB6waR0/2KJfmqfuQo9jpXOmH9em4/bM+rrp2cI0iPdqJ0Mnh93z5DFWXAb+yiG8jGx3GLI3ahfydUEtNCsuJ1ZfBxfstmH7dT0qjDRR4WzfSYlieNo+Yyu9uho0bL9N6P4KUy4MbQuTMUHi+acKbP38TXkWSCdh7O6BDit/sRbuWG8t5zx5QJ3/p9R2vaOVIdAKyNPJv4HxhfsmFGBaLANq+Wq1nm1kGFJiiFxweKYuOXBydirSnwsn/s66Wo4+k2yZj7QRp1NDWHgogvNwu9eRqAKlHpj3wE=
deploy:
  provider: releases
  file_glob: true
  file: output/*.zip
  skip_cleanup: true
  on:
    tags: true
  api_key:
    secure: $GH_TOKEN
